export enum Type {
	SHARE_TYPE_USER = 0,
	SHARE_TYPE_GROUP = 1,
	SHARE_TYPE_LINK = 3,
	SHARE_TYPE_EMAIL = 4,
	SHARE_TYPE_REMOTE = 6,
	SHARE_TYPE_CIRCLE = 7,
	SHARE_TYPE_GUEST = 8,
	SHARE_TYPE_REMOTE_GROUP = 9,
	SHARE_TYPE_ROOM = 10,
	SHARE_TYPE_DECK = 12,
	/**
	 * @since 26.0.0
	 */
	SHARE_TYPE_FEDERATED_GROUP = 14,
}
